# Airflow version to be installed
airflow_version: "2.10.5"

# Python version for the project
python_version: "3.12.3"

# Path to a virtual env
mode:
  name: "uv"
  config:
    venv_path: "/home/mutwiri/airflow/intro/.venv"

# Airflow connections
connections:
    # Example connection
    # - conn_id: example
    #   conn_type: http
    #   host: http://example.com
    #   port: 80
    #   login: user
    #   password: pass
    #   schema: http
    #   extra:
    #      example_extra_field: example-value

# Airflow variables
variables:
    # Example variable
    # - key: example
    #   value: example-value
    #   description: example-description